// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybsojrimjnczipcghsie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlic29qcmltam5jemlwY2doc2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDEyODAsImV4cCI6MjA2NzQ3NzI4MH0.BmrmGu2E8IbskPjGtAu0qqWKilkhk9kblEj2xFeTJXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});